# Generated by Django 4.1 on 2022-10-22 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=200, unique=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('artist', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('album', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
