# syntax=docker/dockerfile:1

FROM python:3.11-buster

ARG APP_NAME
ARG API_VERSION

ARG TMP_UPLOADED_FILES_DIR
ARG MEDIA_DIR
ARG LIBRARIES_DIR_NAME

ARG STATIC_FILES_DIR
ARG STATIC_FILES_DEFAULT_INTERNAL_DIR

ARG DJANGO_LOG_DIR
ARG DJANGO_LOG_GENERAL_FILENAME
ARG DJANGO_LOG_INFO_FILENAME
ARG DJANGO_LOG_REQUESTS_FILENAME
ARG DJANGO_LOG_REQUESTS_DEBUG_FILENAME
ARG DJANGO_LOG_EXCEPTIONS_FILENAME
ARG DJANGO_LOG_DJANGO_FILENAME
ARG DJANGO_LOG_APP_FILENAME

ARG GUNICORN_LOG_DIR
ARG GUNICORN_LOG_ERROR_FILENAME
ARG GUNICORN_LOG_ACCESS_FILENAME

ARG DJANGO_LOG_DIR_SYMLINK_TARGET
ARG MEDIA_DIR_SYMLINK_TARGET
ARG STATIC_FILES_DIR_SYMLINK_TARGET
ARG TMP_UPLOADED_FILES_DIR_SYMLINK_TARGET
ARG GUNICORN_LOG_DIR_SYMLINK_TARGET

RUN for var in \
    AUDIO_META_ANALYSE_IS_NEEDED \
    TMP_UPLOADED_FILES_DIR \
    MEDIA_DIR \
    LIBRARIES_DIR_NAME \
    STATIC_FILES_DIR \
    STATIC_FILES_DEFAULT_INTERNAL_DIR \
    DJANGO_LOG_DIR \
    DJANGO_LOG_GENERAL_FILENAME \
    DJANGO_LOG_INFO_FILENAME \
    DJANGO_LOG_REQUESTS_FILENAME \
    DJANGO_LOG_REQUESTS_DEBUG_FILENAME \
    DJANGO_LOG_EXCEPTIONS_FILENAME \
    DJANGO_LOG_DJANGO_FILENAME \
    DJANGO_LOG_APP_FILENAME \
    GUNICORN_LOG_DIR \
    GUNICORN_LOG_ERROR_FILENAME \
    GUNICORN_LOG_ACCESS_FILENAME \
    DJANGO_LOG_DIR_SYMLINK_TARGET \
    MEDIA_DIR_SYMLINK_TARGET \
    STATIC_FILES_DIR_SYMLINK_TARGET \
    TMP_UPLOADED_FILES_DIR_SYMLINK_TARGET \
    GUNICORN_LOG_DIR_SYMLINK_TARGET; do \
  if [ -z "$(eval echo \$$var)" ]; then \
    echo "The $var argument is not provided" >&2; \
    exit 1; \
  fi; \
done

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DOCKER_HOME=/home/app/webapp \

    ENV=TEST \
    
    DEBUG=true \
    APP_IS_EXPOSED=true \
    AUDIO_META_ANALYSE_IS_NEEDED=true \
    DB_IS_NEEDED=true \

    TMP_UPLOADED_FILES_DIR=$TMP_UPLOADED_FILES_DIR \
    MEDIA_DIR=$MEDIA_DIR \
    LIBRARIES_DIR_NAME=$LIBRARIES_DIR_NAME \

    STATIC_FILES_ARE_NEEDED=true \
    STATIC_FILES_DIR=$STATIC_FILES_DIR \
    STATIC_FILES_DEFAULT_INTERNAL_DIR=$STATIC_FILES_DEFAULT_INTERNAL_DIR \

    DJANGO_LOGS_ARE_NEEDED=true \
    DJANGO_LOG_DIR=$DJANGO_LOG_DIR \
    DJANGO_LOG_GENERAL_FILENAME=$DJANGO_LOG_GENERAL_FILENAME \
    DJANGO_LOG_INFO_FILENAME=$DJANGO_LOG_INFO_FILENAME \
    DJANGO_LOG_REQUESTS_FILENAME=$DJANGO_LOG_REQUESTS_FILENAME \
    DJANGO_LOG_REQUESTS_DEBUG_FILENAME=$DJANGO_LOG_REQUESTS_DEBUG_FILENAME \
    DJANGO_LOG_EXCEPTIONS_FILENAME=$DJANGO_LOG_EXCEPTIONS_FILENAME \
    DJANGO_LOG_DJANGO_FILENAME=$DJANGO_LOG_DJANGO_FILENAME \
    DJANGO_LOG_APP_FILENAME=$DJANGO_LOG_APP_FILENAME \

    GUNICORN_LOG_DIR=$GUNICORN_LOG_DIR \
    GUNICORN_LOG_ERROR_FILENAME=$GUNICORN_LOG_ERROR_FILENAME \
    GUNICORN_LOG_ACCESS_FILENAME=$GUNICORN_LOG_ACCESS_FILENAME \

    DJANGO_LOG_DIR_SYMLINK_TARGET=$DJANGO_LOG_DIR_SYMLINK_TARGET \
    MEDIA_DIR_SYMLINK_TARGET=$MEDIA_DIR_SYMLINK_TARGET \
    STATIC_FILES_DIR_SYMLINK_TARGET=$STATIC_FILES_DIR_SYMLINK_TARGET \
    TMP_UPLOADED_FILES_DIR_SYMLINK_TARGET=$TMP_UPLOADED_FILES_DIR_SYMLINK_TARGET \
    GUNICORN_LOG_DIR_SYMLINK_TARGET=$GUNICORN_LOG_DIR_SYMLINK_TARGET

RUN apt-get update && \
    apt-get install -y gosu && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . $DOCKER_HOME

WORKDIR $DOCKER_HOME

RUN apt update && \
    bash scripts/install_dependencies.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && \
    # The env packages could have been simply copied but the executables wouldn't have been added to the PATH.
    pip install -r requirements.txt && \
    bash scripts/setup_filesystem.sh

RUN pip list | grep gunicorn
RUN echo $PATH && which gunicorn