# syntax=docker/dockerfile:1

# Base Image: Debian Buster (a full Debian distribution).
# Size: Larger, as it includes more tools and libraries by default.
# Use Case: Suitable when you need a full Debian environment with more pre-installed tools and libraries.
FROM python:3.11-buster

ARG ROOT_DIR
ARG APP_NAME
ARG APP_VERSION
ARG DB_CONNECTION_TEST_MAX_ATTEMPTS
ARG DB_CONNECTION_TEST_SLEEP_INTERVAL
ARG TMP_UPLOADED_FILES_DIR
ARG MEDIA_DIR
ARG LIBRARIES_DIR_NAME
ARG STATIC_FILES_DIR
ARG STATIC_FILES_DEFAULT_INTERNAL_DIR
ARG DJANGO_LOG_DIR
ARG DJANGO_LOG_GENERAL_FILENAME
ARG DJANGO_LOG_INFO_FILENAME
ARG DJANGO_LOG_REQUESTS_FILENAME
ARG DJANGO_LOG_REQUESTS_DEBUG_FILENAME
ARG DJANGO_LOG_EXCEPTIONS_FILENAME
ARG DJANGO_LOG_DJANGO_FILENAME
ARG DJANGO_LOG_APP_FILENAME
ARG GUNICORN_LOG_DIR
ARG GUNICORN_LOG_ERROR_FILENAME
ARG GUNICORN_LOG_ACCESS_FILENAME

RUN for var in \
    ROOT_DIR \
    APP_NAME \
    APP_VERSION \
    DB_CONNECTION_TEST_MAX_ATTEMPTS \
    DB_CONNECTION_TEST_SLEEP_INTERVAL \
    TMP_UPLOADED_FILES_DIR \
    MEDIA_DIR \
    LIBRARIES_DIR_NAME \
    STATIC_FILES_DIR \
    STATIC_FILES_DEFAULT_INTERNAL_DIR \
    DJANGO_LOG_DIR \
    DJANGO_LOG_GENERAL_FILENAME \
    DJANGO_LOG_INFO_FILENAME \
    DJANGO_LOG_REQUESTS_FILENAME \
    DJANGO_LOG_REQUESTS_DEBUG_FILENAME \
    DJANGO_LOG_EXCEPTIONS_FILENAME \
    DJANGO_LOG_DJANGO_FILENAME \
    DJANGO_LOG_APP_FILENAME \
    GUNICORN_LOG_DIR \
    GUNICORN_LOG_ERROR_FILENAME \
    GUNICORN_LOG_ACCESS_FILENAME; do \
  if [ -z "$(eval echo \$$var)" ]; then \
    echo "The $var argument is not provided" >&2; \
    exit 1; \
  fi; \
done

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    ROOT_DIR=$ROOT_DIR \
    ENV=TEST \
    APP_NAME=$APP_NAME \
    APP_VERSION=$APP_VERSION \
    DEBUG=true \
    APP_IS_EXPOSED=true \
    AUDIO_META_ANALYSE_IS_NEEDED=true \
    DB_IS_NEEDED=true \
    DB_CONNECTION_TEST_MAX_ATTEMPTS=$DB_CONNECTION_TEST_MAX_ATTEMPTS \
    DB_CONNECTION_TEST_SLEEP_INTERVAL=$DB_CONNECTION_TEST_SLEEP_INTERVAL \
    TMP_UPLOADED_FILES_DIR=$TMP_UPLOADED_FILES_DIR \
    MEDIA_DIR=$MEDIA_DIR \
    LIBRARIES_DIR_NAME=$LIBRARIES_DIR_NAME \
    STATIC_FILES_ARE_NEEDED=true \
    STATIC_FILES_DIR=$STATIC_FILES_DIR \
    STATIC_FILES_DEFAULT_INTERNAL_DIR=$STATIC_FILES_DEFAULT_INTERNAL_DIR \
    DJANGO_LOGS_ARE_NEEDED=true \
    DJANGO_LOG_DIR=$DJANGO_LOG_DIR \
    DJANGO_LOG_GENERAL_FILENAME=$DJANGO_LOG_GENERAL_FILENAME \
    DJANGO_LOG_INFO_FILENAME=$DJANGO_LOG_INFO_FILENAME \
    DJANGO_LOG_REQUESTS_FILENAME=$DJANGO_LOG_REQUESTS_FILENAME \
    DJANGO_LOG_REQUESTS_DEBUG_FILENAME=$DJANGO_LOG_REQUESTS_DEBUG_FILENAME \
    DJANGO_LOG_EXCEPTIONS_FILENAME=$DJANGO_LOG_EXCEPTIONS_FILENAME \
    DJANGO_LOG_DJANGO_FILENAME=$DJANGO_LOG_DJANGO_FILENAME \
    DJANGO_LOG_APP_FILENAME=$DJANGO_LOG_APP_FILENAME \
    GUNICORN_LOG_DIR=$GUNICORN_LOG_DIR \
    GUNICORN_LOG_ERROR_FILENAME=$GUNICORN_LOG_ERROR_FILENAME \
    GUNICORN_LOG_ACCESS_FILENAME=$GUNICORN_LOG_ACCESS_FILENAME

RUN apt-get update && \
    apt-get install -y gosu && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . $ROOT_DIR

WORKDIR $ROOT_DIR

RUN apt update && \
    bash scripts/install_dependencies.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && \
    # The env packages could have been simply copied but the executables wouldn't have been added to the PATH.
    pip install -r requirements.txt && \
    bash scripts/setup_filesystem.sh && \
    chmod +x ${ROOT_DIR}scripts/entrypoint.sh
    
# Set the entrypoint using shell form to allow environment variable expansion
ENTRYPOINT ["sh", "-c", "${ROOT_DIR}scripts/entrypoint.sh"]