version: '3.8'

services:
  web:
    working_dir: /home/app/webapp/
    image: mignot/bodzify-api:latest
    container_name: BODZIFY_API
    restart: always
    command: gunicorn bodzify_api.wsgi:application --config ./gunicorn/gunicorn.conf.py
    volumes:
      - /var/log/bodzify-api/:/var/log/bodzify-api/
      - /var/log/gunicorn/:/var/log/gunicorn/
      - /var/lib/bodzify-api/media/:/var/lib/bodzify-api/media/
    ports:
      - "8000:8000"
  nginx:
    working_dir: /home/app/webapp/
    image: nginx:latest
    container_name: NGINX
    restart: always
    volumes:
      - /var/log/nginx/:/var/log/nginx/
      - /var/www/static/:/var/www/static/
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/bodzify/:/etc/ssl/bodzify/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
