from bodzify_api.model.private_unique_resource.Fields import Fields as PrivateResourceFields


class Fields(PrivateResourceFields):
    NAME_PUBLIC = 'name'
    NAME_INTERNAL = f'_{NAME_PUBLIC}'
    UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL = 'uploaded_tracks_not_archived'
    UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC = 'uploaded_tracks'
    UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL = f'{UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL}_sorted'
    UPLOADED_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC = f'{UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC}_sorted'
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL = f'{UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL}_count'
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = f'{UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC}_count'
    UPLOADED_TRACKS_ARCHIVED_COUNT_INTERNAL = 'uploaded_tracks_archived_count'
    UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC = UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC + '_archived_count'
    DURATION_IN_SEC = 'duration_in_sec'
    DURATION_STR_IN_HOUR_MIN_SEC = 'duration_str_in_hour_min_sec'
