
from api.model.album.Fields import Fields as ModelFields


class Fields:
    CREATED_ON = ModelFields.CREATED_ON
    UPDATED_ON = ModelFields.UPDATED_ON
    UUID = ModelFields.UUID
    NAME_PUBLIC = ModelFields.NAME_PUBLIC
    YEAR = ModelFields.YEAR
    ALBUM_ARTISTS = ModelFields.ALBUM_ARTISTS
    TRACKS_NOT_ARCHIVED_SORTED_INTERNAL = ModelFields.TRACKS_NOT_ARCHIVED_SORTED_INTERNAL
    TRACKS_NOT_ARCHIVED_SORTED_PUBLIC = ModelFields.TRACKS_NOT_ARCHIVED_SORTED_PUBLIC
    TRACKS_NOT_ARCHIVED_COUNT_INTERNAL = ModelFields.TRACKS_NOT_ARCHIVED_COUNT_INTERNAL
    TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = ModelFields.TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    TRACKS_ARCHIVED_COUNT_INTERNAL = ModelFields.TRACKS_ARCHIVED_COUNT_INTERNAL
    TRACKS_ARCHIVED_COUNT_PUBLIC = ModelFields.TRACKS_ARCHIVED_COUNT_PUBLIC
    DURATION_IN_SEC = ModelFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = ModelFields.DURATION_STR_IN_HOUR_MIN_SEC
