from bodzify_api.serializer.model.lib_track.input.Fields import Fields as InputFields


class Fields:
    TRACK_FILE_PUBLIC = InputFields.TRACK_FILE_PUBLIC
    TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE = InputFields.TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE
    TITLE = InputFields.TITLE
    FORCE_TITLE_GENERATION = InputFields.FORCE_TITLE_GENERATION
    ARTISTS_NAMES_ARRAY = InputFields.ARTISTS_NAMES_ARRAY
    ALBUM_NAME = InputFields.ALBUM_NAME
    ALBUM_ARTISTS_NAMES_ARRAY = InputFields.ALBUM_ARTISTS_NAMES_ARRAY
    TRACK_NUMBER = InputFields.TRACK_NUMBER
    GENRE_UUID = InputFields.GENRE_UUID
    GENRE_NAME = InputFields.GENRE_NAME
    RATING = InputFields.RATING
    LANGUAGE = InputFields.LANGUAGE
