class ApiFields:
    class Names:
        ID = 'id'
        NAME = 'name'
        POPULARITY = 'popularity'
        EXTERNAL_URLS = 'external_urls'
        SPOTIFY = 'spotify'
        GENRES = 'genres'
        IMAGES = 'images'
        URL = 'url'
        ARTISTS = 'artists'
        DURATION_MS = 'duration_ms'
        ALBUM = 'album'
        PREVIEW_URL = 'preview_url'
        EXPLICIT = 'explicit'
        ERROR = 'error'
        STATUS = 'status'
        MESSAGE = 'message'
        TRACK = 'track'
        TRACKS = 'tracks'
        ITEMS = 'items'
        FOLLOWERS = 'followers'
        HREF = 'href'
        TYPE = 'type'
        URI = 'uri'
