# Generated by Django 4.1 on 2022-11-04 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodzify_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysong',
            name='uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=200, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodzify_api.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='librarysong',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodzify_api.genre'),
        ),
    ]
