# Generated by Django 5.0.2 on 2025-04-03 15:42

import bodzify_api.model.field
import bodzify_api.model.utils.ConcatOp
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodzify_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('spotify_id', bodzify_api.model.field.AppCharField(max_length=50, unique=True)),
                ('name', bodzify_api.model.field.AppCharField(editable=False, max_length=256)),
                ('popularity', models.IntegerField(editable=False, null=True)),
                ('spotify_link', models.GeneratedField(db_persist=True, expression=bodzify_api.model.utils.ConcatOp.ConcatOp(models.Value('https://open.spotify.com/artist/'), models.F('spotify_id')), output_field=bodzify_api.model.field.AppCharField(max_length=500))),
                ('genres', models.JSONField(editable=False, null=True)),
                ('images', models.JSONField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Spotify Artist',
                'verbose_name_plural': 'Spotify Artists',
                'db_table': 'bodzify_api_spotify_artist',
                'indexes': [models.Index(fields=['spotify_id'], name='sp_artist_id_idx')],
            },
        ),
    ]
