# Generated by Django 4.1 on 2022-11-05 15:43

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bodzify_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='librarytrack',
            name='uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=200, unique=True),
        ),
    ]
