# Generated by Django 4.1 on 2022-11-04 14:57

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bodzify_api', '0002_alter_librarysong_uuid_genre_alter_librarysong_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='librarysong',
            name='uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=200, unique=True),
        ),
    ]
