# Generated by Django 5.0.2 on 2025-04-03 15:58

import bodzify_api.model.field
import bodzify_api.model.field.foreign_key.AppManyToManyField
import bodzify_api.model.utils.ConcatOp
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodzify_api', '0002_spotifyartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('spotify_id', bodzify_api.model.field.AppCharField(max_length=50, unique=True)),
                ('name', bodzify_api.model.field.AppCharField(editable=False, max_length=256)),
                ('duration_ms', models.IntegerField(editable=False)),
                ('popularity', models.IntegerField(editable=False, null=True)),
                ('spotify_link', models.GeneratedField(db_persist=True, expression=bodzify_api.model.utils.ConcatOp.ConcatOp(models.Value('https://open.spotify.com/track/'), models.F('spotify_id')), output_field=bodzify_api.model.field.AppCharField(max_length=500))),
                ('album', models.JSONField(editable=False, null=True)),
                ('preview_url', models.URLField(blank=True, editable=False, max_length=512, null=True)),
                ('explicit', models.BooleanField(default=False, editable=False)),
                ('spotify_artists', bodzify_api.model.field.foreign_key.AppManyToManyField.AppManyToManyField(to='bodzify_api.spotifyartist')),
            ],
            options={
                'verbose_name': 'Spotify Track',
                'verbose_name_plural': 'Spotify Tracks',
                'db_table': 'bodzify_api_spotify_track',
                'indexes': [models.Index(fields=['spotify_id'], name='sp_track_id_idx')],
            },
        ),
    ]
