from bodzify_api.model.playlist.Fields import Fields as PlayListFields


class Fields:
    UUID = PlayListFields.UUID
    USER = PlayListFields.USER
    CREATED_ON = PlayListFields.CREATED_ON
    UPDATED_ON = PlayListFields.UPDATED_ON
    LIB_TRACKS_PUBLIC = PlayListFields.LIB_TRACKS_NOT_ARCHIVED_PUBLIC
    LIB_TRACKS_INTERNAL = PlayListFields.LIB_TRACKS_NOT_ARCHIVED_INTERNAL
    LIB_TRACKS_COUNT_INTERNAL = PlayListFields.LIB_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL
    LIB_TRACKS_COUNT_PUBLIC = PlayListFields.LIB_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    DURATION_IN_SEC = PlayListFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = PlayListFields.DURATION_STR_IN_HOUR_MIN_SEC
    PLAY_COUNT = PlayListFields.PLAY_COUNT
    LAST_TRACK_LIST_UPDATE_DATE = PlayListFields.LAST_TRACK_LIST_UPDATE_DATE
