
from api.model.artist.Fields import Fields as ArtistFields


class Fields:
    CREATED_ON = ArtistFields.CREATED_ON
    UPDATED_ON = ArtistFields.UPDATED_ON
    UUID = ArtistFields.UUID
    NAME_PUBLIC = ArtistFields.NAME_PUBLIC
    ALBUMS = ArtistFields.ALBUMS
    TRACKS_NOT_ARCHIVED_INTERNAL = ArtistFields.TRACKS_NOT_ARCHIVED_INTERNAL
    TRACKS_NOT_ARCHIVED_PUBLIC = ArtistFields.TRACKS_NOT_ARCHIVED_PUBLIC
    TRACKS_NOT_ARCHIVED_COUNT_INTERNAL = ArtistFields.TRACKS_NOT_ARCHIVED_COUNT_INTERNAL
    TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = ArtistFields.TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    TRACKS_ARCHIVED_COUNT_INTERNAL = ArtistFields.TRACKS_ARCHIVED_COUNT_INTERNAL
    TRACKS_ARCHIVED_COUNT_PUBLIC = ArtistFields.TRACKS_ARCHIVED_COUNT_PUBLIC
    DURATION_IN_SEC = ArtistFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = ArtistFields.DURATION_STR_IN_HOUR_MIN_SEC
