
from bodzify_api.model.artist.Fields import Fields as ArtistFields


class Fields:
    CREATED_ON = ArtistFields.CREATED_ON
    UPDATED_ON = ArtistFields.UPDATED_ON
    UUID = ArtistFields.UUID
    NAME_PUBLIC = ArtistFields.NAME_PUBLIC
    ALBUMS = ArtistFields.ALBUMS
    UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL = ArtistFields.UPLOADED_TRACKS_NOT_ARCHIVED_INTERNAL
    UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC = ArtistFields.UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL = ArtistFields.UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = ArtistFields.UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    UPLOADED_TRACKS_ARCHIVED_COUNT_INTERNAL = ArtistFields.UPLOADED_TRACKS_ARCHIVED_COUNT_INTERNAL
    UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC = ArtistFields.UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC
    DURATION_IN_SEC = ArtistFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = ArtistFields.DURATION_STR_IN_HOUR_MIN_SEC
