
from bodzify_api.model.album.Fields import Fields as ModelFields


class Fields:
    CREATED_ON = ModelFields.CREATED_ON
    UPDATED_ON = ModelFields.UPDATED_ON
    UUID = ModelFields.UUID
    NAME = ModelFields.NAME
    YEAR = ModelFields.YEAR
    ALBUM_ARTISTS = ModelFields.ALBUM_ARTISTS
    LIB_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL = ModelFields.LIB_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL
    LIB_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC = ModelFields.LIB_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC
    LIB_TRACKS_NOT_ARCHIVED_COUNT_INTERNAL = ModelFields.LIB_TRACKS_ARCHIVED_COUNT_INTERNAL
    LIB_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = ModelFields.LIB_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    LIB_TRACKS_ARCHIVED_COUNT_INTERNAL = ModelFields.LIB_TRACKS_ARCHIVED_COUNT_INTERNAL
    LIB_TRACKS_ARCHIVED_COUNT_PUBLIC = ModelFields.LIB_TRACKS_ARCHIVED_COUNT_PUBLIC
    DURATION_IN_SEC = ModelFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = ModelFields.DURATION_STR_IN_HOUR_MIN_SEC
