from bodzify_api.model.lib_track_mixin.Fields import Fields as LibTrackMixinFields


class Fields:
    CREATED_ON = LibTrackMixinFields.CREATED_ON
    UPDATED_ON = LibTrackMixinFields.UPDATED_ON
    UUID = LibTrackMixinFields.UUID
    USER = LibTrackMixinFields.USER
    NAME = LibTrackMixinFields.NAME_PUBLIC
    NAME_INTERNAL = LibTrackMixinFields.NAME_INTERNAL
    LIB_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL = LibTrackMixinFields.LIB_TRACKS_NOT_ARCHIVED_SORTED_INTERNAL
    LIB_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC = LibTrackMixinFields.LIB_TRACKS_NOT_ARCHIVED_SORTED_PUBLIC
    LIB_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = LibTrackMixinFields.LIB_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    LIB_TRACKS_ARCHIVED_COUNT_INTERNAL = LibTrackMixinFields.LIB_TRACKS_ARCHIVED_COUNT_INTERNAL
    LIB_TRACKS_ARCHIVED_COUNT_PUBLIC = LibTrackMixinFields.LIB_TRACKS_ARCHIVED_COUNT_PUBLIC
    DURATION_IN_SEC = LibTrackMixinFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = LibTrackMixinFields.DURATION_STR_IN_HOUR_MIN_SEC
    LIB_TRACKS_RELATED_NAME = 'lib_tracks_of_album'
    YEAR = 'year'
    ALBUM_ARTISTS = 'album_artists'
