
from ..Fields import Fields as InoutFields


class Fields:
    TRACK_FILE = InoutFields.TRACK_FILE_PUBLIC
    TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE = InoutFields.TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE
    TITLE = InoutFields.TITLE
    ARTISTS_NAMES_ = InoutFields.ALBUM_ARTISTS_NAMES_ARRAY
    ALBUM_NAME = InoutFields.ALBUM_NAME
    ALBUM_ARTISTS_NAMES_ARRAY = InoutFields.ALBUM_ARTISTS_NAMES_ARRAY
    TRACK_NUMBER = InoutFields.TRACK_NUMBER
    GENRE_UUID = InoutFields.GENRE_UUID
    GENRE_NAME = InoutFields.GENRE_NAME
    RATING = InoutFields.RATING
    LANGUAGE = InoutFields.LANGUAGE
    ARCHIVED = InoutFields.ARCHIVED
