
from ..Fields import Fields as InputFields


class Fields:
    TRACK_FILE = InputFields.TRACK_FILE_PUBLIC
    TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE = InputFields.TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE
    TITLE = InputFields.TITLE
    ARTISTS_NAMES_ = InputFields.ALBUM_ARTISTS_NAMES_ARRAY
    ALBUM_NAME = InputFields.ALBUM_NAME
    ALBUM_ARTISTS_NAMES_ARRAY = InputFields.ALBUM_ARTISTS_NAMES_ARRAY
    TRACK_NUMBER = InputFields.TRACK_NUMBER
    GENRE_UUID = InputFields.GENRE_UUID
    GENRE_NAME = InputFields.GENRE_NAME
    RATING = InputFields.RATING
    LANGUAGE = InputFields.LANGUAGE
    ARCHIVED = InputFields.ARCHIVED
