
from ..Fields import Fields as Fields


class Fields:
    TRACK_FILE = Fields.TRACK_FILE_PUBLIC
    TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE = Fields.TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE
    TITLE = Fields.TITLE
    ARTISTS_NAMES = Fields.ARTISTS_NAMES
    ALBUM_NAME = Fields.ALBUM_NAME
    ALBUM_ARTISTS_NAMES = Fields.ALBUM_ARTISTS_NAMES
    TRACK_NUMBER = Fields.TRACK_NUMBER
    GENRE = Fields.GENRE
    RATING = Fields.RATING
    LANGUAGE = Fields.LANGUAGE
    ARCHIVED = Fields.ARCHIVED
