#!/usr/bin/env python

EXTERNAL_SOURCE_MYFREEMP3 = "myfreemp3"
EXTERNAL_SOURCE_DOESNT_EXIST_MESSAGE = "The specified source doesn\'t exist"

FIELD_QUERY = "query"
FIELD_PAGE = "page"
FIELD_SOURCE = "source"
FIELD_MESSAGE = "message"
FIELD_STATUS = "status"
FIELD_DATA = "data"

FIELD_TITLE = "title"
FIELD_ARTIST = "artist"
FIELD_ALBUM = "album"
FIELD_GENRE = "genre"
FIELD_RATING = "rating"
FIELD_LANGUAGE = "language"
FIELD_DURATION = "duration"
FIELD_URL = "url"
FIELD_DATE = "date"
FIELD_EXTERNAL_SONG_URL = "url"

ID3_TAG_TITLE = "title"
ID3_TAG_ARTIST = "artist"
ID3_TAG_ALBUM = "album"
ID3_TAG_GENRE = "genre"
ID3_TAG_DURATION = "duration"
ID3_TAG_RATING = "titlesort"
ID3_TAG_LANGUAGE = "language"