#!/bin/bash

# Get the directory of the script even when it's called from another script
SCRIPT_DIR=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)/
source "$SCRIPT_DIR../env/.env"

required_vars=(
  ENV
  DOCKERHUB_USERNAME
  TMP_UPLOADED_FILES_DIR
  DB_CONTAINER_NAME
  DB_IMAGE_REPO
  DB_IMAGE_TAG
  DB_DATA_DIR
  DB_PORT
  DB_BODZIFY_API_DB_NAME
  DB_SUPERUSER_NAME
  DB_SUPERUSER_PASSWORD
  AUDIO_FINGERPRINTER_CONTAINER_NAME
  AUDIO_FINGERPRINTER_IMAGE_REPO
  AUDIO_FINGERPRINTER_IMAGE_TAG
  AUDIO_FINGERPRINTER_PORT
  AUDIO_FINGERPRINTER_POOL_DIR_SYMLINK_TARGET
)

for var in "${required_vars[@]}"; do
  if [ -z "${!var}" ]; then
    echo "$var is not set. Please set it in the .env file."
    exit 1
  fi
done

echo "Running the database and audio fingerprinter containers..."

docker pull $DOCKERHUB_USERNAME/$AUDIO_FINGERPRINTER_IMAGE_REPO:$AUDIO_FINGERPRINTER_IMAGE_TAG
docker pull $DOCKERHUB_USERNAME/$DB_IMAGE_REPO:$DB_IMAGE_TAG

docker rm $(docker ps -a -q) -f

docker run \
ty--name=$DB_CONTAINER_NAME \
--volume=db-data:$DB_DATA_DIR \
-p $DB_PORT:$DB_PORT \
-e ENV=$ENV \
-e POSTGRES_DB=$DB_BODZIFY_API_DB_NAME \
-e POSTGRES_USER=$DB_SUPERUSER_NAME\
-e POSTGRES_PASSWORD=$DB_SUPERUSER_PASSWORD \
-e POSTGRES_PORT=$DB_PORT \

docker run -p $AUDIO_FINGERPRINTER_PORT:$AUDIO_FINGERPRINTER_PORT \
ty--name=$AUDIO_FINGERPRINTER_CONTAINER_NAME \
--volume=$TMP_UPLOADED_FILES_DIR:$AUDIO_FINGERPRINTER_POOL_DIR_SYMLINK_TARGET \
-p $AUDIO_FINGERPRINTER_PORT:$AUDIO_FINGERPRINTER_PORT \
-e ENV=$ENV \
-e APP_PORT=$AUDIO_FINGERPRINTER_PORT \
-d $DOCKERHUB_USERNAME/$AUDIO_FINGERPRINTER_IMAGE_REPO:$AUDIO_FINGERPRINTER_IMAGE_TAG \
gunicorn -w 4 -b 0.0.0.0:$AUDIO_FINGERPRINTER_PORT run:app