class Fields:
    UUID = 'uuid'
    NAME = 'name'
    DURATION_MS = 'duration_ms'
    DURATION_STR_IN_HOUR_MIN_SEC = 'duration_str_in_hour_min_sec'
    POPULARITY = 'popularity'
    SPOTIFY_LINK = 'spotify_link'
    ALBUM = 'album'
    PREVIEW_URL = 'preview_url'
    EXPLICIT = 'explicit'
    SPOTIFY_ARTISTS = 'spotify_artists'
    SPOTIFY_ID = 'spotify_id'
    CREATED_ON = 'created_on'
    UPDATED_ON = 'updated_on'
    LAST_SYNCED_AT = 'last_synced_at'
    IS_REMOVED = 'is_removed'
