from api.serializer.model.track.input.Fields import Fields as Fields


class Fields:
    TRACK_FILE_PUBLIC = Fields.TRACK_FILE_PUBLIC
    TITLE = Fields.TITLE
    FORCE_TITLE_GENERATION = Fields.FORCE_TITLE_GENERATION
    ARTISTS_NAMES = Fields.ARTISTS_NAMES
    ARTISTS_NAMES_MULTIPART = Fields.ARTISTS_NAMES_MULTIPART
    ALBUM_NAME = Fields.ALBUM_NAME
    ALBUM_ARTISTS_NAMES = Fields.ALBUM_ARTISTS_NAMES
    ALBUM_ARTISTS_NAMES_MULTIPART = Fields.ALBUM_ARTISTS_NAMES_MULTIPART
    TRACK_NUMBER = Fields.TRACK_NUMBER
    GENRE = Fields.GENRE
    RATING = Fields.RATING
    LANGUAGE = Fields.LANGUAGE
