# Generated by Django 4.1 on 2022-10-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfreemp3api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='artist',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songdb',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='songdb',
            name='duration',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songdb',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songdb',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songdb',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='songdb',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
