# Generated by Django 4.1 on 2022-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfreemp3api', '0002_songdb_artist_songdb_date_songdb_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='album',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
