# Generated by Django 4.1 on 2022-10-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfreemp3api', '0003_songdb_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songdb',
            name='date',
        ),
        migrations.RemoveField(
            model_name='songdb',
            name='language',
        ),
    ]
