# Generated by Django 4.1 on 2022-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfreemp3api', '0004_remove_songdb_date_remove_songdb_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
