# Generated by Django 4.1 on 2022-10-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfreemp3api', '0006_rename_added_on_songdb_addedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='slug',
            field=models.CharField(default='oihoihoihoih', max_length=200),
            preserve_default=False,
        ),
    ]
