# Generated by Django 4.1 on 2022-10-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfreemp3api', '0007_songdb_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songdb',
            old_name='slug',
            new_name='uuid',
        ),
    ]
