# Generated by Django 4.1 on 2022-11-17 13:53

from django.db import migrations

from bodzify_api.model.tag.TagType import TagTypesLabels
from bodzify_api.model.playlist.PlaylistType import PlaylistTypeLabels
from bodzify_api import settings

def populateTagTypes(apps, schemaEditor):
    TagType = apps.get_model('bodzify_api', 'TagType')
    TagType(label=TagTypesLabels.GENRE).save()
    TagType(label=TagTypesLabels.TAG).save()

def populatePlaylistTypes(apps, schemaEditor):
    PlaylistType = apps.get_model('bodzify_api', 'PlaylistType')
    PlaylistType(label=PlaylistTypeLabels.GENRE).save()
    PlaylistType(label=PlaylistTypeLabels.TAG).save()
    PlaylistType(label=PlaylistTypeLabels.CUSTOM).save()

class Migration(migrations.Migration):

    dependencies = [
        ('bodzify_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populateTagTypes),
        migrations.RunPython(populatePlaylistTypes)
    ]
