from bodzify_api.model.playlist.Fields import Fields as BaseFields


class Fields:
    CREATED_ON = BaseFields.CREATED_ON
    UPDATED_ON = BaseFields.UPDATED_ON
    UUID = BaseFields.UUID
    USER = BaseFields.USER
    NAME = BaseFields.NAME
    LIB_TRACKS = BaseFields.LIB_TRACKS
    LIB_TRACKS_COUNT = BaseFields.LIB_TRACKS_COUNT
    LIB_TRACKS_NOT_ARCHIVED = BaseFields.LIB_TRACKS_NOT_ARCHIVED
    LIB_TRACKS_ARCHIVED_COUNT = BaseFields.LIB_TRACKS_ARCHIVED_COUNT
    DURATION_IN_SEC = BaseFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = BaseFields.DURATION_STR_IN_HOUR_MIN_SEC
    PLAY_COUNT = BaseFields.PLAY_COUNT
    LAST_TRACK_LIST_UPDATE_DATE = BaseFields.LAST_TRACK_LIST_UPDATE_DATE
