class Fields:
    ID = 'id'
    USERNAME = 'username'
    PASSWORD = 'password'
    EMAIL = 'email'
    IS_TEST_USER = 'is_test_user'
    IS_STAFF = 'is_staff'
    IS_SUPERUSER = 'is_superuser'
    GROUPS = 'groups'
    USER_PERMISSIONS = 'user_permissions'
    ALL_TRACK_MIXIN = 'all_tracks_mixin'
