name: API CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: 
      - main
      - dev
      - prevent-posting-same-track
  pull_request:
    branches: [main, dev]

env:
  SSH_DESTINATION: ${{ secrets.TEST_SERVER_BODZIFY_USERNAME }}@${{ vars.TEST_SERVER_URL }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  CONTAINER_ROOT_DIR: /home/app/
  DB_CONNECTION_TEST_MAX_ATTEMPTS: 10
  DB_CONNECTION_TEST_SLEEP_INTERVAL: 5

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    environment: 
      name: CI_TEST
    env:
      ENV: ${{ vars.ENV }}
      APP_NAME: ${{ vars.APP_NAME }}
      APP_VERSION: ${{ vars.APP_VERSION }}
      DOCKER_NETWORK_NAME: ${{ vars.DOCKER_NETWORK_NAME }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DEBUG: true
      DB_IS_NEEDED: true
      APP_IS_EXPOSED: false
      TMP_UPLOADED_FILES_EXTERNAL: ${{ vars.TMP_UPLOADED_FILES_EXTERNAL }}
      ACOUSTID_API_KEY: ${{ secrets.ACOUSTID_API_KEY }}
      MEDIA_DIR_INTERNAL: ${{ vars.MEDIA_DIR_INTERNAL }}
      LIBRARIES_DIR_NAME: ${{ vars.LIBRARIES_DIR_NAME }}
      DB_IMAGE_REPO: ${{ vars.DB_IMAGE_REPO }}
      DB_VERSION: ${{ vars.DB_VERSION }}
      DB_CONTAINER_NAME: ${{ vars.DB_CONTAINER_NAME }}
      DB_DATA_DIR: ${{ vars.DB_DATA_DIR }}
      DB_SUPERUSER_NAME: ${{ vars.DB_SUPERUSER_NAME }}
      DB_SUPERUSER_PASSWORD: ${{ secrets.DB_SUPERUSER_PASSWORD }}
      DB_BODZIFY_API_DB_NAME: ${{ secrets.DB_BODZIFY_API_DB_NAME }}
      DB_BODZIFY_API_USERNAME: ${{ secrets.DB_BODZIFY_API_USERNAME }}
      DB_BODZIFY_API_USER_PASSWORD: ${{ secrets.DB_BODZIFY_API_USER_PASSWORD }}
      DB_URL: ${{ vars.DB_URL }}
      DB_PORT: ${{ vars.DB_PORT }}
      AFP_IMAGE_REPO: ${{ vars.AFP_IMAGE_REPO }}
      AFP_VERSION: ${{ vars.AFP_VERSION }}
      AFP_CONTAINER_NAME: ${{ vars.AFP_CONTAINER_NAME }}
      AFP_PORT: ${{ vars.AFP_PORT }}
      AFP_POOL_DIR_EXTERNAL: ${{ vars.AFP_POOL_DIR_EXTERNAL }}
      AFP_POST_ENDPOINT: ${{ vars.AFP_POST_ENDPOINT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Cache apt packages
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('scripts/install_dependencies.sh') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: sudo -E bash scripts/install_dependencies.sh

      - name: Add fpcalc to PATH
        run: echo "bin/fpcalc" >> $GITHUB_PATH

      - name: Install requirements
        run: PIP_NO_CACHE_DIR=off pip install -r requirements.txt

      - name: Set up filesystem
        run: bash scripts/setup_filesystem.sh

      - name: Run database and Audio Fingerprint containers
        env:
          DB_DATA_MUST_PERSIST: false
        run: bash scripts/run_db_and_afp_containers.sh

      - name: Wait for database service to start
        run: bash scripts/wait-for-postgres-db.sh ${{ env.DB_URL }} ${{ env.DB_PORT }} ${{ env.DB_CONNECTION_TEST_MAX_ATTEMPTS }} ${{ env.DB_CONNECTION_TEST_SLEEP_INTERVAL }}

      - name: Init django data
        run: bash scripts/init_django_data.sh

      - name: Run pytest
        run: pytest

  collect-and-push-static-files:
    name: Collect and push static files
    runs-on: ubuntu-latest
    # needs: [pytest]
    environment: 
      name: COLLECT_STATIC
    env:
      ENV: ${{ vars.ENV }}
      APP_NAME: ${{ vars.APP_NAME }}
      APP_VERSION: ${{ vars.APP_VERSION }}
      DEBUG: false
      DB_IS_NEEDED: false
      APP_IS_EXPOSED: false
      STATIC_FILES_INTERNAL: ${{ vars.STATIC_FILES_INTERNAL }}
    outputs:
      output1: ${{ steps.commit-and-push-static-Files.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up filesystem
        run: bash scripts/setup_filesystem.sh

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit and push static files
        id: commit-and-push-static-Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git diff --staged --exit-code || git commit -am "Add collected static files"          
          git push

          # Output the commit hash so that it can be used in the next job
          echo "collect_static_files_commit_hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  build-and-push-to-dockerhub:
    name: Build / Push to Dockerhub
    runs-on: ubuntu-latest
    needs: [collect-and-push-static-files]
    environment: 
      name: TEST
    env:
      IMAGE_FULL_NAME: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APP_IMAGE_REPO }}:${{ vars.APP_VERSION }}
      IMAGE_URL: https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.WEB_SERVER_IMAGE_REPO }}/tags/${{ vars.APP_VERSION }}/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches to retrieve the commit from collect-and-push-static-files

      - name: Checkout specific commit
        env: 
          COLLECT_STATIC_FILES_COMMIT_HASH: ${{ needs.collect-and-push-static-files.outputs.collect_static_files_commit_hash }}
        run: |
          git checkout ${{ env.COLLECT_STATIC_FILES_COMMIT_HASH }}

      - name: Display last commit message
        run: git log -1 --pretty=format:"%s"

      - name: List files
        run: ls -la

      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | \
          docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_FULL_NAME }}
          build-args: |
            ROOT_DIR=${{ env.CONTAINER_ROOT_DIR }}
            APP_NAME=${{ vars.APP_NAME }}
            APP_VERSION=${{ vars.APP_VERSION }}
            DB_CONNECTION_TEST_MAX_ATTEMPTS=${{ env.DB_CONNECTION_TEST_MAX_ATTEMPTS }}
            DB_CONNECTION_TEST_SLEEP_INTERVAL=${{ env.DB_CONNECTION_TEST_SLEEP_INTERVAL }}
            TMP_UPLOADED_FILES_EXTERNAL=${{ vars.TMP_UPLOADED_FILES_EXTERNAL }}
            MEDIA_DIR_EXTERNAL=${{ vars.MEDIA_DIR_EXTERNAL }}
            LIBRARIES_DIR_NAME=${{ vars.LIBRARIES_DIR_NAME }}
            STATIC_FILES_EXTERNAL=${{ vars.STATIC_FILES_EXTERNAL }}
            STATIC_FILES_INTERNAL=${{ vars.STATIC_FILES_INTERNAL }}
            DJANGO_LOG_DIR_EXTERNAL=${{ vars.DJANGO_LOG_DIR_EXTERNAL }}
            DJANGO_LOG_GENERAL_FILENAME=${{ vars.DJANGO_LOG_GENERAL_FILENAME }}
            DJANGO_LOG_INFO_FILENAME=${{ vars.DJANGO_LOG_INFO_FILENAME }}
            DJANGO_LOG_REQUESTS_FILENAME=${{ vars.DJANGO_LOG_REQUESTS_FILENAME }}
            DJANGO_LOG_REQUESTS_DEBUG_FILENAME=${{ vars.DJANGO_LOG_REQUESTS_DEBUG_FILENAME }}
            DJANGO_LOG_EXCEPTIONS_FILENAME=${{ vars.DJANGO_LOG_EXCEPTIONS_FILENAME }}
            DJANGO_LOG_DJANGO_FILENAME=${{ vars.DJANGO_LOG_DJANGO_FILENAME }}
            DJANGO_LOG_APP_FILENAME=${{ vars.DJANGO_LOG_APP_FILENAME }}
            GUNICORN_LOG_DIR=${{ vars.GUNICORN_LOG_DIR }}
            GUNICORN_LOG_ERROR_FILENAME=${{ vars.GUNICORN_LOG_ERROR_FILENAME }}
            GUNICORN_LOG_ACCESS_FILENAME=${{ vars.GUNICORN_LOG_ACCESS_FILENAME }}

  set-env-variables-on-server:
    name: Set environment variables on server
    runs-on: ubuntu-latest
    # needs: [build-and-push-to-dockerhub]
    environment: 
      name: TEST
    env:
      DOCKER_COMPOSE_DIR: ${{ vars.WEBHOOK_DIR }}${{ vars.WEBHOOK_REDEPLOYMENT_DIR_NAME }}/${{ vars.DOCKER_COMPOSE_DIR_NAME }}/
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SERVER_SSH_BODZIFY_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh &&
          ssh-keyscan -H ${{ vars.TEST_SERVER_URL }} >> ~/.ssh/known_hosts

      - name: Set api environment variables on server
        env: 
          API_ENV_FILE: "${{ env.DOCKER_COMPOSE_DIR }}${{ vars.D