name: API CI

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: 
        - main
        - dev
        - prevent-posting-same-track
    pull_request:
        branches: [main, dev]

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    env:
      ENV: GITHUB_CI_TEST
      DEBUG: True
      SECRET_KEY: ${{ secrets.CI_TEST_SECRET_KEY }}

      DB_CONTAINER_NAME: ${{ vars.CI_TEST_DB_CONTAINER_NAME }}
      DB_SUPERUSER_NAME: ${{ secrets.CI_TEST_DB_SUPERUSER_NAME }}
      DB_SUPERUSER_PASSWORD: ${{ secrets.CI_TEST_DB_SUPERUSER_PASSWORD }}
      DB_BODZIFY_API_DB_NAME: ${{ secrets.CI_TEST_DB_BODZIFY_API_DB_NAME }}
      DB_BODZIFY_API_USERNAME: ${{ secrets.CI_TEST_DB_BODZIFY_API_USERNAME }}
      DB_BODZIFY_API_USER_PASSWORD: ${{ secrets.CI_TEST_DB_BODZIFY_API_USER_PASSWORD }}
      DB_HOST: ${{ secrets.CI_TEST_DB_HOST }}
      DB_PORT: ${{ secrets.CI_TEST_DB_PORT }}

      AUDIO_FINGERPRINTER_PORT: ${{ secrets.TEST_AUDIO_FINGERPRINTER_PORT }}
      ACOUSTID_API_KEY: ${{ secrets.CI_TEST_ACOUSTID_API_KEY }}

    services:
      audio-fingerprinter:
        image: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.AUDIO_FINGERPRINTER_IMAGE_REPO }}:${{ vars.AUDIO_FINGERPRINTER_IMAGE_TAG }}
        ports:
          - 3000
        volumes:
          - /tmp/bodzify-api/uploaded-files/:/tmp/bodzify-audio-fingerprinter/pool/
        env:
          ENV: TEST
          APP_PORT: ${{ secrets.TEST_AUDIO_FINGERPRINTER_PORT }}

      db:
        image: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DB_IMAGE_REPO }}:${{ vars.DB_IMAGE_TAG }}
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.DB_BODZIFY_API_DB_NAME }}
          POSTGRES_USER: ${{ env.DB_SUPERUSER_NAME }}
          POSTGRES_PASSWORD: ${{ env.DB_SUPERUSER_PASSWORD }}
          POSTGRES_PORT: ${{ env.DB_PORT }}
        options: >-
          --name=${{ vars.CI_TEST_DB_CONTAINER_NAME }}
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3
    steps:
      - name: Wait for db service to start
        run: sleep 30
      - name: Ping db
        run: ping db
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
           python-version: 3.11

      - name: Install requirements
        run: PIP_NO_CACHE_DIR=off pip install -r requirements.txt

      - name: Install chromaprint
        run: sudo apt-get install libchromaprint-tools

      - name: Install flac
        run: sudo apt-get install flac # apt not stable for CLI interface

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Add fpcalc to PATH
        run: echo "${{ github.workspace }}/bin/fpcalc" >> $GITHUB_PATH

      - name: Set up filesystem
        run: bash scripts/filesystem/filesystem_setup.github_ci_test.sh

      - name: Init data
        run: ${{ github.workspace }}/scripts/data/data_init.github_ci_test.sh

      - name: Run pytest
        run: pytest

  build-and-push-to-dockerhub:
    name: Build / Push to Dockerhub
    runs-on: ubuntu-latest
    needs: [pytest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DB_IMAGE_REPO }}:${{ vars.DB_IMAGE_TAG }}

  set-env-variables-on-server:
    name: Set environment variables on server
    runs-on: ubuntu-latest
    needs: [build-and-push-to-dockerhub]
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SERVER_CI_SSH_BODZIFY_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh &&
          ssh-keyscan -H ${{ vars.TEST_SERVER_URL }} >> ~/.ssh/known_hosts

      - name: Set environment variables on server
        run: |
          ENV_FILE_PATH="${{ vars.DOCKER_COMPOSE_DIR }}${{ vars.API_ENV_VARIABLES_FILENAME }}"
          ssh ${{ secrets.TEST_SERVER_SSH_BODZIFY_USERNAME }}@${{ vars.TEST_SERVER_URL }} "
            rm -f $ENV_FILE_PATH &&
            echo 'ENV=TEST' >> $ENV_FILE_PATH &&
            echo 'DJANGO_SECRET_KEY=${{ secrets.TEST_DJANGO_SECRET_KEY }}' >> $ENV_FILE_PATH &&
            echo 'DB_USERNAME=${{ secrets.TEST_DB_BODZIFY_API_USERNAME }}' >> $ENV_FILE_PATH && 
            echo 'DB_PASSWORD=${{ secrets.TEST_DB_BODZIFY_API_USER_PASSWORD }}' >> $ENV_FILE_PATH &&
            echo 'DB_DATABASE=${{ secrets.TEST_DB_BODZIFY_API_DB_NAME }}' >> $ENV_FILE_PATH &&
            echo 'DB_HOST=${{ secrets.TEST_DB_HOST }}' >> $ENV_FILE_PATH &&
            echo 'DB_PORT=${{ secrets.TEST_DB_PORT }}' >> $ENV_FILE_PATH &&
            echo 'ACOUSTID_API_KEY=${{ secrets.ACOUSTID_API_KEY }}' >> $ENV_FILE_PATH &&
            echo 'TEST_AUDIO_FINGERPRINTER_PORT=${{ secrets.TEST_AUDIO_FINGERPRINTER_PORT }}' >> $ENV_FILE_PATH &&
          "

  redeploy-webhook-call:
    name: Redeploy webhook call
    needs: [set-env-variables-on-server]
    uses: Bodzify/bodzify-redeploy-webhook-action/.github/workflows/workflow.yml@main
    with:
      env: TEST
    secrets: inherit
