name: API CI

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: 
        - main
        - dev
        - prevent-posting-same-track
    pull_request:
        branches: [main, dev]

env:
  SSH_DESTINATION: ${{ secrets.TEST_SERVER_BODZIFY_USERNAME }}@${{ vars.TEST_SERVER_URL }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  IMAGE_REPO: ${{ vars.API_IMAGE_REPO }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}
  API_ENV_FILENAME: ${{ vars.API_ENV_FILENAME }}

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    environment: 
      name: CI_TEST
    env:
      ENV: CI_TEST
      DEBUG: True
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

      DB_CONTAINER_NAME: ${{ vars.DB_CONTAINER_NAME }}
      DB_SUPERUSER_NAME: ${{ secrets.DB_SUPERUSER_NAME }}
      DB_SUPERUSER_PASSWORD: ${{ secrets.DB_SUPERUSER_PASSWORD }}
      DB_BODZIFY_API_DB_NAME: ${{ secrets.DB_BODZIFY_API_DB_NAME }}
      DB_BODZIFY_API_USERNAME: ${{ secrets.DB_BODZIFY_API_USERNAME }}
      DB_BODZIFY_API_USER_PASSWORD: ${{ secrets.DB_BODZIFY_API_USER_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

      AUDIO_FINGERPRINTER_PORT: ${{ secrets.AUDIO_FINGERPRINTER_PORT }}
      ACOUSTID_API_KEY: ${{ secrets.ACOUSTID_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
           python-version: 3.11

      - name: Install requirements
        run: PIP_NO_CACHE_DIR=off pip install -r requirements.txt

      - name: Install chromaprint
        run: sudo apt-get install libchromaprint-tools

      - name: Install flac
        run: sudo apt-get install flac # apt not stable for CLI interface

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Add fpcalc to PATH
        run: echo "${{ github.workspace }}/bin/fpcalc" >> $GITHUB_PATH

      - name: Set up filesystem
        run: bash scripts/filesystem_setup.sh

      - name: Run audio-fingerprinter service
        run: |
          docker run -d \
            -p ${{ env.AUDIO_FINGERPRINTER_PORT}}:${{ env.AUDIO_FINGERPRINTER_PORT}} \
            -v ${{ env.TEMP_UPLOADED_FILES_DIR }}:${{ vars.AUDIO_FINGERPRINTER_POOL_DIR }} \
            -e ENV=TEST \
            -e APP_PORT=${{ env.AUDIO_FINGERPRINTER_PORT }} \
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.AUDIO_FINGERPRINTER_IMAGE_REPO }}:${{ vars.AUDIO_FINGERPRINTER_IMAGE_TAG }}

      - name: Run db service
        run: |
          docker run -d \
            -p ${{ env.DB_PORT}}:${{ env.DB_PORT}} \
            -e POSTGRES_DB=${{ env.DB_BODZIFY_API_DB_NAME }} \
            -e POSTGRES_USER=${{ env.DB_SUPERUSER_NAME }} \
            -e POSTGRES_PASSWORD=${{ env.DB_SUPERUSER_PASSWORD }} \
            -e POSTGRES_PORT=${{ env.DB_PORT }} \
            --name=${{ env.DB_CONTAINER_NAME }} \
            --health-cmd="pg_isready" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            ${{ env.DOCKERHUB_USERNAME }}/${{ vars.DB_IMAGE_REPO }}:${{ vars.DB_IMAGE_TAG }}
        
      - name: Wait for db service to start
        run: |
          attempts=0
          max_attempts=5
          while ! pg_isready -h localhost -p ${{ env.DB_PORT }}; do
            if [ $attempts -eq $max_attempts ]; then
              echo "DB service did not start within the expected time."
              exit 1
            fi
            echo "Waiting for DB service to start..."
            sleep 15
            attempts=$((attempts+1))
          done

      - name: Init db
        run: ${{ github.workspace }}/scripts/data/db_init.sh
        
      - name: Init django data
        run: ${{ github.workspace }}/scripts/data/django_data_init.sh

      - name: Run pytest
        run: pytest

  build-and-push-to-dockerhub:
    name: Build / Push to Dockerhub
    runs-on: ubuntu-latest
    # needs: [pytest]
    environment: 
      name: TEST
    env:
      # manage.py collectstatic needs all the app's env variables
      ENV: COLLECT_STATIC
      DEBUG: False
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

      DB_SUPERUSER_NAME: ${{ secrets.DB_SUPERUSER_NAME }}
      DB_SUPERUSER_PASSWORD: ${{ secrets.DB_SUPERUSER_PASSWORD }}
      DB_BODZIFY_API_DB_NAME: ${{ secrets.DB_BODZIFY_API_DB_NAME }}
      DB_BODZIFY_API_USERNAME: ${{ secrets.DB_BODZIFY_API_USERNAME }}
      DB_BODZIFY_API_USER_PASSWORD: ${{ secrets.DB_BODZIFY_API_USER_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

      AUDIO_FINGERPRINTER_PORT: ${{ secrets.TEST_AUDIO_FINGERPRINTER_PORT }}
      ACOUSTID_API_KEY: ${{ secrets.ACOUSTID_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | \
          docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      # Needed for collectstatic
      - name: Set up filesystem
        run: bash scripts/filesystem_setup.sh

      # Requirements installation is not in the dockerfile because it is needed by the static files collecting
      - name: Install requirements
        run: |
          pip install --upgrade pip && \
          pip install -r requirements.txt --cache-dir /opt/bodzify-api/pip_cache

      # As collecting static files uses manage.py which is part of the app, the app's env variables are needed. As 
      # passing env variables to a dockerfile poses risks, we do that in the CI.
      - name: Collect static files
        run: python ${{ github.workspace }}/manage.py collectstatic --noinput

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          build-args: |
            DJANGO_LOG_DIR=${{ vars.APP_LOG_DIR }}${{ vars.DJANGO_LOG_DIR_NAME }}
            GUNICORN_LOG_DIR=${{ vars.APP_LOG_DIR }}${{ vars.GUNICORN_LOG_DIR_NAME }}
            LIBRARIES_DIR=${{ vars.MEDIA_DIR }}${{ vars.LIBRARIES_DIR_NAME }}
            TEMP_UPLOADED_FILES_DIR=${{ vars.TEMP_UPLOADED_FILES_DIR }}
            STATIC_FILES_DIR: ${{ vars.STATIC_FILES_DIR }}

  set-env-variables-on-server:
    name: Set environment variables on server
    runs-on: ubuntu-latest
    # needs: [build-and-push-to-dockerhub]
    environment: 
      name: TEST
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SERVER_SSH_BODZIFY_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh &&
          ssh-keyscan -H ${{ vars.TEST_SERVER_URL }} >> ~/.ssh/known_hosts

      - name: Set api environment variables on server
        env: 
          API_ENV_FILE_PATH: "${{ vars.DOCKER_COMPOSE_DIR }}${{ env.API_ENV_FILENAME }}"
        run: |
          ssh ${{ env.SSH_DESTINATION }} "
            rm -f ${{ env.API_ENV_FILE_PATH }} &&
            echo 'ENV=TEST' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DEBUG=True' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'MEDIA_DIR=${{ vars.MEDIA_DIR }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'LIBRARIES_DIR_NAME=${{ vars.LIBRARIES_DIR_NAME }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DJANGO_LOG_DIR=${{ vars.DJANGO_LOG_DIR }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DB_CONTAINER_NAME=${{ vars.DB_CONTAINER_NAME }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DB_BODZIFY_API_DB_NAME=${{ secrets.DB_BODZIFY_API_DB_NAME }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DB_BODZIFY_API_USERNAME=${{ secrets.DB_BODZIFY_API_USERNAME }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DB_BODZIFY_API_USER_PASSWORD=${{ secrets.DB_BODZIFY_API_USER_PASSWORD }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DB_HOST=${{ secrets.DB_HOST }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'DB_PORT=${{ secrets.DB_PORT }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'ACOUSTID_API_KEY=${{ secrets.ACOUSTID_API_KEY }}' >> ${{ env.API_ENV_FILE_PATH }} &&
            echo 'AUDIO_FINGERPRINTER_PORT=${{ secrets.TEST_AUDIO_FINGERPRINTER_PORT }}' >> ${{ env.API_ENV_FILE_PATH }}
          "

      # POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB and POSTGRES_PORT env variables are required by the postgres image
      - name: Set db environment variables on server
        env:
          DB_ENV_FILE_PATH: "${{ vars.DOCKER_COMPOSE_DIR }}${{ vars.DB_ENV_FILENAME }}"
        run: |
          ssh ${{ env.SSH_DESTINATION }} "
            rm -f ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'DB_HOST=localhost' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'DB_SUPERUSER_NAME=${{ secrets.DB_SUPERUSER_NAME }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'POSTGRES_USER=${{ secrets.DB_SUPERUSER_NAME }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'DB_SUPERUSER_PASSWORD=${{ secrets.DB_SUPERUSER_PASSWORD }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'POSTGRES_PASSWORD=${{ secrets.DB_SUPERUSER_PASSWORD }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'DB_BODZIFY_API_DB_NAME=${{ secrets.DB_BODZIFY_API_DB_NAME }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'POSTGRES_DB=${{ secrets.DB_BODZIFY_API_DB_NAME }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'DB_BODZIFY_API_USERNAME=${{ secrets.DB_BODZIFY_API_USERNAME }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'DB_BODZIFY_API_USER_PASSWORD=${{ secrets.DB_BODZIFY_API_USER_PASSWORD }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'DB_PORT=${{ secrets.DB_PORT }}' >> ${{ env.DB_ENV_FILE_PATH }} &&
            echo 'POSTGRES_PORT=${{ secrets.DB_PORT }}' >> ${{ env.DB_ENV_FILE_PATH }}
          "

      - name: Set audio fingerprinter environment variables on server
        env:
          AUDIO_FINGERPRINTER_ENV_FILE_PATH: "${{ vars.DOCKER_COMPOSE_DIR }}${{ vars.AUDIO_FINGERPRINTER_ENV_FILENAME }}"
        run: |
          ssh ${{ env.SSH_DESTINATION }} "
            rm -f ${{ env.AUDIO_FINGERPRINTER_ENV_FILE_PATH }} &&
            echo 'ENV=TEST' >> ${{ env.AUDIO_FINGERPRINTER_ENV_FILE_PATH }} &&
            echo 'APP_PORT=${{ secrets.APP_PORT }}' >> ${{ env.AUDIO_FINGERPRINTER_ENV_FILE_PATH }}
          "

  set-partial-docker-compose-on-server:
    name: Set partial docker-compose on server
    runs-on: ubuntu-latest
    # needs: [build-and-push-to-dockerhub]
    environment: 
      name: TEST
    env:
      DOCKER_COMPOSE_PART_FILENAME: ${{ vars.DOCKER_COMPOSE_PART_FILENAME }}
      APP_PORT: ${{ secrets.APP_PORT }}

    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SERVER_SSH_BODZIFY_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh &&
          ssh-keyscan -H ${{ vars.TEST_SERVER_URL }} >> ~/.ssh/known_hosts

      - name: Generate partial docker compose file
        env: 
          CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
        run: |
          bash ${{ github.workspace }}/scripts/generate_docker_compose_part.sh

      - name: Transfer partial docker-compose on server
        run: |
          scp ${{ github.workspace }}/scripts/${{ env.DOCKER_COMPOSE_PART_FILENAME }} ${{ env.SSH_DESTINATION }}:\
          ${{ vars.DOCKER_COMPOSE_DIR }}${{ vars.DOCKER_COMPOSE_PARTS_DIR_NAME }}/${{ env.DOCKER_COMPOSE_PART_FILENAME }}

  redeploy-webhook-call:
    name: Redeploy webhook call
    needs: [set-env-variables-on-server, set-partial-docker-compose-on-server]
    uses: Bodzify/bodzify-server-management/.github/workflows/call-redeployment-webhook.yml@main
    with:
      env: TEST
    secrets: inherit
