name: Validation and Deployment

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [dev]
    pull_request:
        branches: [dev]

jobs:
  Pytest:
    runs-on: ubuntu-latest
    env:
      ENV: DEV
      DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      DB_HOST: ${{ secrets.DEV_UNDOCKERIZED_DB_HOST }}
      DB_DATABASE: ${{ secrets.DEV_DB_DATABASE }}
      DB_PORT: ${{ secrets.DEV_DB_PORT }}
    services:
      postgres_main:
        image: postgres:14.5
        env:
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_DATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
           python-version: 3.11
      - name: Install requirements
        run: |
            pip install -r bodzify_api/requirements.txt
      - name: Set up filesystem
        run: |
            bash scripts/setup_filesystem_workflow.sh
      - name: Run pytest
        run: |
            pytest .

  flake8:
    name: flake8
    needs: Pytest
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8 . --exclude=migrations/ --max-line-length=100

  Docker-webapp:
    name: Publish Docker Hub - Webapp
    runs-on: ubuntu-latest
    needs: [pytest]
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_WEBAPP_REPO }}
      DOCKER_IMAGE_TAG: ${{ secrets.DOCKER_IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build Docker image
        run:
          docker-compose -f bodzify_api/docker-compose.build.yml build
          --build-arg secretKey='${{ secrets.PROD_DJANGO_SECRET_KEY }}' 
          --build-arg secretKey='${{ secrets.PROD_DJANGO_SECRET_KEY }}' 
          --build-arg secretKey='${{ secrets.PROD_DJANGO_SECRET_KEY }}' 
          --build-arg env=TEST 
          --build-arg dbUsername=${{ secrets.PROD_DB_USERNAME }}
          --build-arg dbPassword='${{ secrets.PROD_DB_PASSWORD }}'
          --build-arg dbDatabase=${{ secrets.PROD_DB_DATABASE }}
          --build-arg dbHost=${{ secrets.PROD_DOCKERIZED_DB_HOST }}
          --build-arg dbPort=${{ secrets.PROD_DB_PORT }}
      - name: Publish Docker image
        run: docker-compose -f bodzify_api/docker-compose.build.yml push

  Docker-nginx:
    name: Publish Docker Hub - Nginx
    runs-on: ubuntu-latest
    needs: [pytest]
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_NGINX_REPO }}
      DOCKER_IMAGE_TAG: ${{ secrets.DOCKER_IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build Docker image
        run:
          docker-compose -f nginx/docker-compose.build.yml build
          --build-arg secretKey='${{ secrets.PROD_DJANGO_SECRET_KEY }}' 
          --build-arg secretKey='${{ secrets.PROD_DJANGO_SECRET_KEY }}' 
          --build-arg secretKey='${{ secrets.PROD_DJANGO_SECRET_KEY }}' 
          --build-arg env=TEST 
          --build-arg dbUsername=${{ secrets.PROD_DB_USERNAME }}
          --build-arg dbPassword='${{ secrets.PROD_DB_PASSWORD }}'
          --build-arg dbDatabase=${{ secrets.PROD_DB_DATABASE }}
          --build-arg dbHost=${{ secrets.PROD_DOCKERIZED_DB_HOST }}
          --build-arg dbPort=${{ secrets.PROD_DB_PORT }}
      - name: Publish Docker image
        run: docker-compose -f nginx/docker-compose.build.yml push

  Redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [Docker-webapp, Docker-nginx]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
